name: Update List
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python3.14-bookworm-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run generation script
        env:
          DONETICK_TOKEN: ${{ secrets.DONETICK_TOKEN }}
          DONETICK_USERNAME: ${{ secrets.DONETICK_USERNAME }}
          DONETICK_PASSWORD: ${{ secrets.DONETICK_PASSWORD }}
          GH_PAT: ${{ secrets.GH_PAT }}
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        run: uv run ./generate_html.py
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4